### ISSUE TITLE
Style Restaurant Pages

### ISSUE THREAD

**Issue by casslee1351** [casslee1351/DjangoRepo#3]
1.  Add styling for restaurant name and address
2.  Scrape Google for addresses and website results
3.  Include MapIt button (if possible)
4.  Area for photo

**Comment by yongyx** [comment]
Hi, I would like to contribute on this project and had a few questions.
1. What kind of styling would you want?
2. Is the web scraping only for a particular location?

**Comment by casslee1351** [comment]
Thank you for reaching out!!
I am from Wichita, Kansas so my project is focusing on the local
restaurants in this area. I am still trying to gather information for the
actual database, so I haven't decided how I'd want the pages to be styled
yet.
I haven't done a lot of planning so I am just trying to figure it out as I
go along.

**Comment by yongyx** [comment]
That's fine! I am thinking for the database how about web scraping using a Yelp API? I could try and code a algorithm to get a database.

**Comment by casslee1351** [comment]
Yes! I've been playing around with that idea, but haven't quite gotten to
it so that would actually be very helpful!!

P.S. I'm actually surprised you reached out, I didn't think anybody would
see it or care enough to contribute :)

**Comment by casslee1351** [comment]
Also, thought I should mention,
There's some dummy data I will have to clean up that I used for testing, so
something might seem a little weird if you see it.

**Comment by yongyx** [comment]
I found this issue while scrolling through other issues, so I would be glad to help!

**Comment by casslee1351** [comment]
Thank you so much, the help is much appreciated. I'm excited to see
what you come up with! Feel free to let me know if you have any questions!
